"""add missing columns to articles

Revision ID: 4fb3b9f1cb50
Revises: 
Create Date: 2026-05-03 18:10:31.937926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb3b9f1cb50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculated_amount', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('external_status', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_applications_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subsidiary_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reading_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_is_published'), ['is_published'], unique=False)
        batch_op.create_foreign_key(None, 'subsidiaries', ['subsidiary_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('current_version', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by_user_id'], ['id'])

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_news_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)
        batch_op.create_foreign_key(None, 'subsidiaries', ['subsidiary_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_document_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_foreign_key(None, 'documents', ['related_document_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_priority', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('form_schema_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount_min',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('amount_max',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('timeline',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_services_category'))
        batch_op.create_index(batch_op.f('ix_services_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_subsidiary_id'), ['subsidiary_id'], unique=False)
        batch_op.create_foreign_key(None, 'subsidiaries', ['subsidiary_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'form_schemas', ['form_schema_id'], ['id'])
        batch_op.drop_column('category')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('iin_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('organization_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('can_sign', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_sign_financial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_first_head', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('egov_subject', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ecp_certificate_serial', sa.String(length=120), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_bin_number'), ['bin_number'], unique=False)
        batch_op.create_unique_constraint(None, ['egov_subject'])
        batch_op.create_unique_constraint(None, ['iin_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_bin_number'))
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('ecp_certificate_serial')
        batch_op.drop_column('egov_subject')
        batch_op.drop_column('is_first_head')
        batch_op.drop_column('can_sign_financial')
        batch_op.drop_column('can_sign')
        batch_op.drop_column('position')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('iin_number')
        batch_op.drop_column('phone')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_services_subsidiary_id'))
        batch_op.drop_index(batch_op.f('ix_services_category_id'))
        batch_op.create_index(batch_op.f('ix_services_category'), ['category'], unique=False)
        batch_op.alter_column('timeline',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('rate',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('amount_max',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('amount_min',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('form_schema_id')
        batch_op.drop_column('is_published')
        batch_op.drop_column('is_priority')
        batch_op.drop_column('category_id')
        batch_op.drop_column('result')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_column('payload')
        batch_op.drop_column('related_document_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_news_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_is_published'))
        batch_op.alter_column('slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_published')
        batch_op.drop_column('type')
        batch_op.drop_column('cover_url')
        batch_op.drop_column('summary')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'applications', ['application_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('current_version')
        batch_op.drop_column('signed_at')
        batch_op.drop_column('uploaded_by_user_id')
        batch_op.drop_column('review_comment')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('checksum')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_articles_is_published'))
        batch_op.drop_index(batch_op.f('ix_articles_category'))
        batch_op.alter_column('category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_published')
        batch_op.drop_column('reading_time')
        batch_op.drop_column('cover_url')
        batch_op.drop_column('subsidiary_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('summary')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_external_id'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('external_status')
        batch_op.drop_column('external_id')
        batch_op.drop_column('calculated_amount')

    # ### end Alembic commands ###
